name: Build KSUN Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4

      - name: Set up Build Environment
        run: |
          sudo sed -i 's/azure.archive.ubuntu.com/archive.ubuntu.com/g' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y build-essential bc libncurses5-dev libssl-dev libelf-dev bison flex zip curl git gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-arm-linux-gnueabi g++-arm-linux-gnueabi clang lld

      - name: Download Toolchain (Proton Clang)
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang

      - name: Integrate KernelSU Next
        run: |
          export GIT_TERMINAL_PROMPT=0
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/master/kernel/setup.sh" | bash -s master

      - name: Fix KernelSU patch_memory error
        run: |
          sed -i 's/copy_to_kernel_nofault/probe_kernel_write/g' drivers/kernelsu/hook/arm64/patch_memory.c


      - name: Build Kernel
        run: |
          export PATH="$(pwd)/clang/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          
          mkdir -p out
          
          DEFCONFIG_FILE=$(find arch/arm64/configs/ -type f \( -name "*ruby*defconfig" -o -name "*mt6877*defconfig" \) | head -n 1 | sed 's|arch/arm64/configs/||')
          echo "Using defconfig: $DEFCONFIG_FILE"
          
          echo "CONFIG_KSU=y" >> arch/arm64/configs/$DEFCONFIG_FILE
          echo "CONFIG_KPROBES=y" >> arch/arm64/configs/$DEFCONFIG_FILE
          echo "CONFIG_HAVE_KPROBES=y" >> arch/arm64/configs/$DEFCONFIG_FILE
          echo "CONFIG_KPROBE_EVENTS=y" >> arch/arm64/configs/$DEFCONFIG_FILE
          
          make O=out ARCH=arm64 $DEFCONFIG_FILE
          
          make -j$(nproc --all) O=out ARCH=arm64 \
               CC=clang \
               CLANG_TRIPLE=aarch64-linux-gnu- \
               CROSS_COMPILE=aarch64-linux-gnu- \
               CROSS_COMPILE_ARM32=arm-linux-gnueabi-
               
      - name: Pack with AnyKernel3
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git AK3
          cp out/arch/arm64/boot/Image.gz-dtb AK3/ || cp out/arch/arm64/boot/Image.gz AK3/ || cp out/arch/arm64/boot/Image AK3/
          cd AK3
          sed -i 's/device.name1=maguro/device.name1=ruby/' anykernel.sh
          zip -r9 ../KSUN-Kernel-rubyx.zip * -x "*.git*" README.md *placeholder

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KSUN-Kernel-rubyx
          path: KSUN-Kernel-rubyx.zip
